# Generated by Django 4.1.4 on 2023-01-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of the booking', max_length=256)),
                ('guest_number', models.SmallIntegerField(default=1, help_text='Number of the guests')),
                ('date', models.DateTimeField(help_text='Booking date')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Title of the menu', max_length=256)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the menu', max_digits=10)),
                ('inventory', models.SmallIntegerField(default=10, help_text='Number of items in the inventory')),
            ],
        ),
    ]
