# Generated by Django 4.1.4 on 2023-01-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='MenuItem',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['id']},
        ),
    ]
